version: "3"

volumes:
  filescloud:
    driver: local
  mysqlowncloud:
    driver: local
  redisowncloud:
    driver: local

services:
  owncloud:
    image: owncloud/server:latest
    container_name: owncloud_server
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - mariadb
      - redis
    environment:
      - OWNCLOUD_DOMAIN=http://nhanbpxcmag.ddns.net
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=94p4uQLDBOLE9PLsFnwomPOF5cMc4rNuIN
      - OWNCLOUD_DB_HOST=mariadb
      - OWNCLOUD_ADMIN_USERNAME=admin
      - OWNCLOUD_ADMIN_PASSWORD=Luckystar1209@
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /mnt/sdb1/owncloud_data:/mnt/data/files

  mariadb:
    image: mariadb
    container_name: owncloud_mariadb
    restart: always
    ports:
      - 33061:3306
    environment:
      - MYSQL_ROOT_PASSWORD=94p4uQLDBOLE9PLsFnwomPOF5cMc4rNuIN
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=94p4uQLDBOLE9PLsFnwomPOF5cMc4rNuIN
      - MYSQL_DATABASE=owncloud
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=owncloud"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysqlowncloud:/var/lib/mysql

  redis:
    image: redis
    container_name: owncloud_redis
    restart: always
    ports:
      - 63800:6380
    command: ["--databases", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redisowncloud:/data
