version: '3.9'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    ports:
      - 33060:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=2mJYZrmF11ubLbuWHD14SHB6seq9
      - MYSQL_PASSWORD=ZrmF11ubLbuWHD14SHB6seq9
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 8888:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
      - /mnt/sdb1/nextcloud_data:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=ZrmF11ubLbuWHD14SHB6seq9
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      
